language: generic
sudo: required
services:
  - docker

before_install: 
  - docker build -t shastakouski/docker-react -f Dockerfile.dev .
 
script:
  - docker run -e CI=true shastakouski/docker-react npm run test -- --coverage